### ISSUE TITLE
勘误

### ISSUE THREAD

**Issue by ache123** [PotoYang/spring-in-action-v5-translate#12]
程序清单 2.4，参数不是Design类而是Taco类

**Comment by ghost** [comment]
> 程序清单 2.4，参数不是Design类而是Taco类

![image](https://user-images.githubusercontent.com/61682136/95554688-2e408900-0a43-11eb-815f-7036c3ba60fd.png)

原作者要么写的是伪代码，要么就是写错了，自己修改修改吧
