### ISSUE TITLE
gitbook中有个错误没有与github中的同步修改

### ISSUE THREAD

**Issue by MomentDerek** [PotoYang/spring-in-action-v5-translate#2]
![image](https://user-images.githubusercontent.com/40252940/76580676-c4dbb480-650b-11ea-8920-9191d457321a.png)
![image](https://user-images.githubusercontent.com/40252940/76580680-cc9b5900-650b-11ea-92ed-2592ff5b621f.png)

**Comment by PotoYang** [comment]
Solve
