### ISSUE TITLE
问下原版英文电子书在哪里看？

### ISSUE THREAD

**Issue by LjyYano** [PotoYang/spring-in-action-v5-translate#21]
问下原版英文电子书在哪里看？同时您这个翻译速度是什么样的？

**Comment by MASTERPlECE** [comment]
链接: https://pan.baidu.com/s/1r4s0A1vhkGwehy5lbCKHng
提取码: 2333
不客气

**Comment by tolerious** [comment]
> 2333



> 链接: https://pan.baidu.com/s/1r4s0A1vhkGwehy5lbCKHng 提取码: 2333 不客气

失效了。
