### ISSUE TITLE
很多语句缺少主语,  不符合中文文法

### ISSUE THREAD

**Issue by Likenttt** [PotoYang/spring-in-action-v5-translate#29]
**PotoYang** , hi,
感谢你们的翻译工作. 我注意到许多语句缺少主语. 虽然可以理解, 但是我觉得有失严谨.例如
>  随着 Taco Cloud 应用程序的增长，将使用 Java 代码、图像、样式表、测试以及其他可帮助完成项目的附带材料来填充此准系统的项目结构。

**Comment by LeonLi0102** [comment]
多提pr，把这些修正修正。

**Comment by Likenttt** [comment]
> 多提pr，把这些修正修正。
好,既然你们认可,那我就在阅读的过程中顺手纠正了.
