### ISSUE TITLE
@PotoYang, plz add my name to Contributors List.

### ISSUE THREAD

**Issue by LeonLi0102** [PotoYang/spring-in-action-v5-translate#33]

**Comment by PotoYang** [comment]
Maybe your local git doesn't configure correctly. You can read this article([why-are-my-contributions-not-showing-up-on-my-profile](https://docs.github.com/en/github/setting-up-and-managing-your-github-profile/why-are-my-contributions-not-showing-up-on-my-profile)). And modify some configuration then you can try again.

**Comment by PotoYang** [comment]
I have added your Github Account in README.MD. It shows Contributors.

**Comment by LeonLi0102** [comment]
My bad. I am using company laptop to do all the translatation. The git configuration "user.email“ on that is my company mail address which do not match my github account setting.
