### ISSUE TITLE
14.4.2 的图片资源失效

### ISSUE THREAD

**Issue by WangShuXian6** [PotoYang/spring-in-action-v5-translate#44]
>14.4.2 文章中的两张图片均无法显示

**Comment by LeonLi0102** [comment]
感谢反馈!
我检查了一下，我的git提交是没问题的，图片文件都提到 asset下边了。
现在gitbook页面中，14.4.1以后的图都没有在gitbook页面正确显示。

这种显示正常：
https://gblobscdn.gitbook.com/assets%2F-LrmLE3NwQoVJk02Q_BX%2Fsync%2Fc45358f5e48fe6691d9391f05ed6b1cdd331b89d.png?alt=media


这种显示不了：
https://github.com/PotoYang/spring-in-action-v5-translate/tree/2ef0750b9d6f8ff952b03a39a8321db64c3c24c6/.gitbook/assets/14.3.png

是生成gitbook页面的时候，又重新上传了一下图床？ 处理一下吧。 ​@PotoYang

**Comment by PotoYang** [comment]
已解决
