### ISSUE TITLE
书中2.1.2的DesignTacoController代码中缺少函数

### ISSUE THREAD

**Issue by apnos** [PotoYang/spring-in-action-v5-translate#5]
缺少了一个filterByType函数，我在别的书中看见是有写这个函数的，希望可以加上以便他人学习。
```java
private List<Ingredient> filterByType(List<Ingredient> ingredients, Type type) {
        return ingredients.stream().filter(x -> x.getType().equals(type)).collect(Collectors.toList());
}
```

**Comment by PotoYang** [comment]
可以的，请提交一个PR就行

**Comment by apnos** [comment]
以后注意了 之前没有提交过，现在了解了
---原始邮件---
发件人:"PotoYang"<notifications@github.com>
发送时间:2020年4月24日 星期五 上午9:37
收件人:"PotoYang/spring-in-action-v5-translate"<spring-in-action-v5-translate@noreply.github.com>
抄送:"晓松丶"<aexiaosong@qq.com>;"Author"<author@noreply.github.com>
主题:Re: [PotoYang/spring-in-action-v5-translate] 书中2.1.2的DesignTacoController代码中缺少函数 (#5)



可以的，请提交一个PR就行

&mdash;
